// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (
    uuid,
    amount,
    currency,
    payment_method,
    nonprofit_id,
    donor_id,
    status,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING uuid, amount, currency, payment_method, nonprofit_id, donor_id, status, created_at, updated_at
`

type CreateDonationParams struct {
	Uuid          uuid.UUID
	Amount        int64
	Currency      string
	PaymentMethod string
	NonprofitID   string
	DonorID       string
	Status        string
	CreatedAt     time.Time
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createDonation,
		arg.Uuid,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.NonprofitID,
		arg.DonorID,
		arg.Status,
		arg.CreatedAt,
	)
	var i Donation
	err := row.Scan(
		&i.Uuid,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.NonprofitID,
		&i.DonorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDonation = `-- name: GetDonation :one
SELECT uuid, amount, currency, payment_method, nonprofit_id, donor_id, status, created_at, updated_at
FROM donations
WHERE uuid = $1
`

func (q *Queries) GetDonation(ctx context.Context, argUuid uuid.UUID) (Donation, error) {
	row := q.db.QueryRow(ctx, getDonation, argUuid)
	var i Donation
	err := row.Scan(
		&i.Uuid,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.NonprofitID,
		&i.DonorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDonations = `-- name: ListDonations :many
SELECT uuid, amount, currency, payment_method, nonprofit_id, donor_id, status, created_at, updated_at
FROM donations
ORDER BY created_at DESC, uuid DESC
`

func (q *Queries) ListDonations(ctx context.Context) ([]Donation, error) {
	rows, err := q.db.Query(ctx, listDonations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.Uuid,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.NonprofitID,
			&i.DonorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonationStatus = `-- name: UpdateDonationStatus :one
UPDATE donations
SET
    status = $2,
    updated_at = $3
WHERE uuid = $1
RETURNING uuid, amount, currency, payment_method, nonprofit_id, donor_id, status, created_at, updated_at
`

type UpdateDonationStatusParams struct {
	Uuid      uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateDonationStatus(ctx context.Context, arg UpdateDonationStatusParams) (Donation, error) {
	row := q.db.QueryRow(ctx, updateDonationStatus, arg.Uuid, arg.Status, arg.UpdatedAt)
	var i Donation
	err := row.Scan(
		&i.Uuid,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.NonprofitID,
		&i.DonorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
